services:
  avr:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    devices:
      - "/dev/bus/usb/003/002:/dev/bus/usb/003/002"
    privileged: true
    working_dir: /app
